Repository TEAM-BIDI/bidi, pull requests merged in 2021-09, with the labels that each got.

#89 landing/로그인/회원가입 redux 적용완료
  client/src/Api/branding.js
  client/src/Api/common.js
  client/src/Contexts/User/action.js
  client/src/Contexts/User/constant.js
  client/src/Contexts/User/reducer.js
  client/src/Navigator/MainTab/mainTabStack.js
  client/src/Screen/01_FirstTab/User/designerListScreen.js
  client/src/Screen/Auth/loginScreen.js
  client/src/Screen/Auth/registerScreen.js
  client/src/Screen/landingScreen.js
  client/yarn.lock
  server/app.js
  server/lib/asyncWrapper.js
  server/lib/elasticsearch.js
  server/package-lock.json
  server/package.json
  server/routes/branding/controller.js
  server/routes/user/controller.js
  server/routes/user/index.js
  server/services/branding.js
  server/services/db/bid.js
  server/services/db/branding.js
  server/services/user.js
Labels: 🖼️ frontend, 👨‍👨‍👧‍👦 discussion

#90 User/FirstTab refactoring 완료
  client/ios/bidi.xcodeproj/project.pbxproj
  client/src/Api/matching.js
  client/src/Api/styleScrap.js
  client/src/Components/Card/cardStyle.js
  client/src/Components/HeaderBar/topLeftBar.js
  client/src/Components/MatchingHistory/DesignerReview.js
  client/src/Components/Modal/styleModal.js
  client/src/Contexts/Branding/action.js
  client/src/Contexts/Branding/constant.js
  client/src/Contexts/Branding/index.js
  client/src/Contexts/Branding/reducer.js
  client/src/Contexts/Common/asyncUtils.js
  client/src/Contexts/Common/globalStore.js
  client/src/Contexts/Matching/action.js
  client/src/Contexts/Matching/constant.js
  client/src/Contexts/Matching/reducer.js
  client/src/Contexts/StyleScrap/action.js
  client/src/Contexts/StyleScrap/constant.js
  client/src/Contexts/StyleScrap/index.js
  client/src/Contexts/StyleScrap/reducer.js
  client/src/Lib/utils.js
  client/src/Navigator/MainTab/User/proposalTabScreen.js
  client/src/Navigator/MainTab/User/searchTabScreen.js
  client/src/Navigator/MainTab/mainTabStack.js
  client/src/Screen/01_FirstTab/User/designerDetailScreen.js
  client/src/Screen/01_FirstTab/User/designerHistoryScreen.js
  client/src/Screen/01_FirstTab/User/designerListScreen.js
  client/src/Screen/01_FirstTab/User/designerStyleScreen.js
  client/src/Screen/Auth/loginScreen.js
  client/src/Screen/Auth/registerScreen.js
  server/routes/matching/controller.js
  server/routes/matching/index.js
Labels: 🖼️ frontend, 🚀refactor

#93 [refactor] Feature/designer/third tab 리팩토링 완료
  client/src/Api/branding.js
  client/src/Api/common.js
  client/src/Api/style.js
  client/src/Api/user.js
  client/src/Components/ListItem/itemContent.js
  client/src/Components/ListItem/mainItemCard.js
  client/src/Components/StyleBook/styleCategory.js
  client/src/Components/StyleBook/styleDescription.js
  client/src/Components/StyleBook/styleImage.js
  client/src/Components/StyleBook/styleMain.js
  client/src/Components/StyleBook/stylePrice.js
  client/src/Components/StyleBook/styleTags.js
  client/src/Components/StyleBook/styleTitle.js
  client/src/Contexts/Bid/action.js
  client/src/Contexts/Bid/constant.js
  client/src/Contexts/Bid/reducer.js
  client/src/Contexts/Branding/action.js
  client/src/Contexts/Branding/constant.js
  client/src/Contexts/Branding/reducer.js
  client/src/Contexts/Common/globalStore.js
  client/src/Contexts/Style/action.js
  client/src/Contexts/Style/constant.js
  client/src/Contexts/Style/index.js
  client/src/Contexts/Style/reducer.js
  client/src/Contexts/User/action.js
  client/src/Lib/constant.js
  client/src/Lib/utils.js
  client/src/Navigator/MainTab/Designer/brandingTabScreen.js
  client/src/Screen/01_FirstTab/Designer/createBidScreen.js
  client/src/Screen/01_FirstTab/Designer/proposalListScreen.js
  client/src/Screen/02_SecondTab/Designer/bidMainScreen.js
  client/src/Screen/02_SecondTab/Designer/processBidListScreen.js
  client/src/Screen/02_SecondTab/Designer/waitBidListScreen.js
  client/src/Screen/03_ThirdTab/Designer/brandingListScreen.js
  client/src/Screen/03_ThirdTab/Designer/brandingMainScreen.js
  client/src/Screen/03_ThirdTab/Designer/createBrandingScreen.js
  client/src/Screen/03_ThirdTab/Designer/createStyleBookScreen.js
  client/src/Screen/03_ThirdTab/Designer/deatailStyleBookScreen.js
  client/src/Screen/03_ThirdTab/Designer/detailBrandingScreen.js
  client/src/Screen/03_ThirdTab/Designer/editBrandingScreen.js
  client/src/Screen/03_ThirdTab/Designer/editStyleBookScreen.js
  client/src/Screen/03_ThirdTab/Designer/noStyleBookScreen.js
  client/src/Screen/03_ThirdTab/Designer/styleBookListScreen.js
  client/src/Screen/03_ThirdTab/Designer/styleBookScreen.js
  client/src/Screen/Auth/registerScreen.js
  client/yarn.lock
  server/app.js
  server/middleware/uploadStyle.js
  server/routes/branding/controller.js
  server/routes/branding/index.js
  server/routes/style/controller.js
  server/routes/style/index.js
  server/services/bid.js
  server/services/branding.js
  server/services/db/branding.js
  server/services/db/style.js
  server/services/style.js
Labels: 🚀refactor

#103 디자이너 마이페이지 구현
  client/src/Api/user.js
  client/src/Components/Common/line.js
  client/src/Lib/constant.js
  client/src/Lib/utils.js
  client/src/Navigator/MainTab/Designer/myPageTabScreen.js
  client/src/Screen/01_FirstTab/Designer/createBidScreen.js
  client/src/Screen/05_MypageTab/designer/detailMypageScreen.js
  client/src/Screen/05_MypageTab/designer/myPageScreen.js
  client/src/Screen/Auth/registerScreen.js
  server/routes/user/controller.js
  server/routes/user/index.js
  server/services/user.js
Labels: 🖼️ frontend, 🚀refactor

#115 자잘한 이슈 해결
  client/src/Components/Bid/bidRefStyle.js
  client/src/Components/Bid/styleModal.js
  client/src/Components/Branding/designerHistory.js
  client/src/Components/Branding/designerStyle.js
  client/src/Components/Card/cardInfo.js
  client/src/Components/Card/cardStyle.js
  client/src/Components/HeaderBar/addressBar.js
  client/src/Components/ListItem/itemContent.js
  client/src/Navigator/MainTab/Designer/bidTabScreen.js
  client/src/Navigator/MainTab/Designer/searchTabScreen.js
  client/src/Screen/01_FirstTab/Customer/TabScreen/designerHairShopInfoScreen.js
  client/src/Screen/01_FirstTab/Customer/designerDetailScreen.js
  client/src/Screen/01_FirstTab/Designer/createBidScreen.js
  client/src/Screen/01_FirstTab/Designer/styleListScreen.js
  client/src/Screen/02_SecondTab/Designer/detailBidScreen.js
  client/src/Screen/03_ThirdTab/Designer/Branding/brandingScreen.js
  server/routes/bid/controller.js
  server/routes/branding/controller.js
  server/services/bid.js
  server/services/branding.js
  server/services/db/bid.js
  server/services/db/branding.js
Labels: 🚀refactor
