Repository TEAM-BIDI/bidi, pull requests merged in 2021-07, with the labels that each got.

#4 #6 - User Register 구현
  .github/ISSUE_TEMPLATE.md
  client/src/Screen/Auth/loginScreen.js
  client/src/Screen/Auth/registerScreen.js
  server/app.js
  server/models/user.js
  server/routes/user/controller.js
  server/routes/user/index.js
  server/services/db/user.js
  server/services/user.js
Labels: 📚 api, 📡 backend, 🖼️ frontend

#11 User API, Mypage 구현
  client/App.js
  client/package-lock.json
  client/package.json
  client/src/Components/topRightBar.js
  client/src/Lib/constant.js
  client/src/Lib/storage.js
  client/src/Screen/Auth/registerScreen.js
  client/src/Screen/landingScreen.js
  client/src/Screen/mypageScreen.js
  client/yarn.lock
  server/lib/constants.js
  server/routes/user/controller.js
  server/routes/user/index.js
  server/services/db/user.js
  server/services/user.js
Labels: 📚 api, 📡 backend, 🖼️ frontend

#14 bidi로 project 이름 변경
  client/.gitignore
  client/App.js
  client/android/app/BUCK
  client/android/app/build.gradle
  client/android/app/src/debug/java/com/biidi/ReactNativeFlipper.java
  client/android/app/src/main/AndroidManifest.xml
  client/android/app/src/main/java/com/biidi/MainActivity.java
  client/android/app/src/main/java/com/biidi/MainApplication.java
  client/android/app/src/main/res/values/strings.xml
  client/android/settings.gradle
  client/app.json
  client/ios/Podfile
  client/ios/SwiftBridge.swift
  client/ios/bidi-Bridging-Header.h
  client/ios/bidi.xcodeproj/project.pbxproj
  client/ios/bidi.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  client/ios/bidi.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  client/ios/bidi.xcodeproj/xcshareddata/xcschemes/bidi.xcscheme
  client/ios/bidi.xcworkspace/contents.xcworkspacedata
  client/ios/bidi.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  client/ios/bidi/AppDelegate.h
  client/ios/bidi/AppDelegate.m
  client/ios/bidi/Images.xcassets/AppIcon.appiconset/1024.png
  client/ios/bidi/Images.xcassets/AppIcon.appiconset/120-1.png
  client/ios/bidi/Images.xcassets/AppIcon.appiconset/120.png
  client/ios/bidi/Images.xcassets/AppIcon.appiconset/180.png
  client/ios/bidi/Images.xcassets/AppIcon.appiconset/40.png
  client/ios/bidi/Images.xcassets/AppIcon.appiconset/58.png
  client/ios/bidi/Images.xcassets/AppIcon.appiconset/60.png
  client/ios/bidi/Images.xcassets/AppIcon.appiconset/80.png
  client/ios/bidi/Images.xcassets/AppIcon.appiconset/87.png
  client/ios/bidi/Images.xcassets/AppIcon.appiconset/Contents.json
  client/ios/bidi/Images.xcassets/Contents.json
  client/ios/bidi/LaunchScreen.storyboard
  client/ios/bidi/main.m
  client/ios/bidiTests/Info.plist
  client/ios/bidiTests/bidiTests.m
  client/ios/biidi-Bridging-Header.h
  client/package-lock.json
  client/package.json
  client/public/img/landing_logo.png
  client/public/img/logo.png
  client/src/Components/topLeftBar.js
  client/src/Components/topRightBar.js
  client/src/Screen/Auth/loginScreen.js
  client/src/Screen/landingScreen.js
  client/src/Screen/mainScreen.js
  client/src/Screen/mypageScreen.js
  client/yarn.lock
  server/public/stylesheets/style.css
  server/views/error.ejs
  server/views/index.ejs
Labels: 🐞 bugfix

#15 logout, swipe library 설치
  client/App.js
  client/ios/bidi.xcodeproj/project.pbxproj
  client/ios/bidi.xcworkspace/contents.xcworkspacedata
  client/package-lock.json
  client/package.json
  client/src/Navigator/Tab/AdminTabScreen.js
  client/src/Navigator/Tab/messageTabScreen.js
  client/src/Navigator/Tab/searchTabScreen.js
  client/src/Navigator/Tab/viidTabScreen.js
  client/src/Navigator/authStack.js
  client/src/Screen/ViidTab/viidScreen.js
  client/src/Screen/biidScreen.js
  client/src/Screen/landingScreen.js
  client/src/Screen/mypageScreen.js
  client/yarn.lock
Labels: 🖼️ frontend

#20 Feature/proposal
  client/ios/bidi.xcodeproj/project.pbxproj
  client/public/img/proposal_intro.png
  client/src/Navigator/Tab/proposalTabScreen.js
  client/src/Screen/ViidTab/viidScreen.js
  client/src/Screen/proposal/intro.js
  client/src/Screen/proposalScreen.js
  server/models/index.js
  server/models/keyword.js
  server/models/proposal.js
  server/models/relation/proposalKeyword.js
  server/routes/index.js
  server/routes/proposal/controller.js
  server/routes/proposal/index.js
  server/services/db/proposal.js
  server/services/proposal.js
Labels: 📚 api, 📡 backend, 🖼️ frontend

#23 Feature/proposal
  client/App.js
  client/ios/bidi.xcodeproj/project.pbxproj
  client/package.json
  client/public/img/proposal_after_image.png
  client/public/img/proposal_registered.png
  client/src/Navigator/Tab/proposalTabScreen.js
  client/src/Navigator/mainTabStack.js
  client/src/Screen/ProposalTab/checkingProposal.js
  client/src/Screen/ProposalTab/createProposal.js
  client/src/Screen/ProposalTab/introProposal.js
  client/src/Screen/ProposalTab/registeredProposal.js
  client/src/Screen/ProposalTab/selectAfterImage.js
  client/src/Screen/ProposalTab/selectFromAlbum.js
  client/src/Screen/ProposalTab/selectFromBidi.js
  client/src/Screen/ProposalTab/selectFromScrap.js
  client/src/Screen/mainScreen.js
  client/src/Screen/mypageScreen.js
  client/src/Screen/proposalScreen.js
  client/yarn.lock
  server/config/config.js
  server/models/proposal.js
  server/routes/proposal/controller.js
  server/routes/proposal/index.js
  server/services/db/proposal.js
  server/services/proposal.js
Labels: 📚 api, 📡 backend, 🖼️ frontend

#25 s3연동 및 data 생성
  client/App.js
  client/package-lock.json
  client/src/Components/Designer/designerInfo.js
  client/src/Navigator/Tab/myPageTabScreen.js
  client/src/Navigator/mainTabStack.js
  client/src/Screen/Auth/registerScreen.js
  client/src/Screen/MypageTab/mypageScreen.js
  client/src/Screen/mypageScreen.js
  client/yarn.lock
  server/.env.sample
  server/middleware/upload.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/routes/user/controller.js
  server/routes/user/index.js
  server/services/branding.js
  server/services/db/branding.js
  server/services/db/user.js
  server/services/user.js
Labels: 📚 api, 📡 backend, 🖼️ frontend
