Repository TEAM-BIDI/bidi, pull requests merged in 2021-08, with the labels that each got.

#32 제안서 스와이프/비드 작성
  client/public/img/finish_biid.jpg
  client/src/Components/Card/cardInfo.js
  client/src/Components/Card/cardStyle.js
  client/src/Components/Card/recommendStyle.js
  client/src/Components/Designer/designerStyle.js
  client/src/Navigator/MainTab/Designer/searchTabScreen.js
  client/src/Navigator/MainTab/Designer/temp.js
  client/src/Navigator/MainTab/designerTabStack.js
  client/src/Navigator/MainTab/mainTabStack.js
  client/src/Screen/BidTab/user/bidListScreen.js
  client/src/Screen/SearchTab/Designer/createBiidScreen.js
  client/src/Screen/SearchTab/Designer/index.js
  client/src/Screen/SearchTab/Designer/proposalDetailScreen.js
  client/src/Screen/SearchTab/Designer/proposalListScreen.js
  client/src/Screen/SearchTab/Designer/registeredBiidScreen.js
  client/src/Screen/SearchTab/User/designerDetailScreen.js
  client/src/Screen/SearchTab/User/designerListScreen.js
  server/models/index.js
  server/models/proposal.js
  server/routes/proposal/controller.js
  server/routes/proposal/index.js
  server/services/branding.js
  server/services/db/proposal.js
  server/services/proposal.js
Labels: 📚 api, 🖼️ frontend

#40 Bid 작성 API 수정
  client/src/Components/Card/cardInfo.js
  client/src/Components/Card/cardStyle.js
  client/src/Lib/constant.js
  client/src/Lib/utils.js
  client/src/Navigator/MainTab/mainTabStack.js
  client/src/Screen/01_FirstTab/Designer/createBidScreen.js
  client/src/Screen/01_FirstTab/Designer/proposalDetailScreen.js
  client/src/Screen/01_FirstTab/Designer/proposalListScreen.js
  client/src/Screen/01_FirstTab/User/designerListScreen.js
  client/src/Screen/02_SecondTab/User/bidListScreen.js
  client/src/Screen/Auth/loginScreen.js
  client/src/Screen/Auth/registerScreen.js
  client/yarn.lock
  server/routes/bid/controller.js
  server/routes/bid/index.js
  server/routes/index.js
  server/routes/proposal/controller.js
  server/routes/user/controller.js
  server/services/bid.js
  server/services/db/bid.js
Labels: 📚 api, 📡 backend

#44 스타일 스크랩 기능 구현
  client/public/img/noScrap.png
  client/src/Navigator/MainTab/User/historyTabScreen.js
  client/src/Screen/01_FirstTab/User/designerStyleScreen.js
  client/src/Screen/03_ThirdTab/User/createProposalScreen.js
  client/src/Screen/04_FourthTab/User/bidScreen.js
  client/src/Screen/04_FourthTab/User/historyMainScreen.js
  client/src/Screen/04_FourthTab/User/introStyleScrapScreen.js
  client/src/Screen/04_FourthTab/User/styleScrapScreen.js
  server/models/index.js
  server/models/relation/styleScrap.js
  server/routes/index.js
  server/routes/styleScrap/controller.js
  server/routes/styleScrap/index.js
  server/routes/user/controller.js
  server/services/db/styleScrap.js
  server/services/styleScrap.js
  server/services/user.js
Labels: 📚 api, 📡 backend, 🖼️ frontend

#56 [Designer-ThirdTab] 브랜딩 페이지 작성
  client/App.js
  client/ios/bidi.xcodeproj/project.pbxproj
  client/package-lock.json
  client/public/img/branding_intro.png
  client/src/Components/Bid/bidListItem.js
  client/src/Components/Branding/brandingInput.js
  client/src/Components/Card/cardInfo.js
  client/src/Components/Card/cardStyle.js
  client/src/Components/Common/temp.js
  client/src/Components/HeaderBar/topLeftBar.js
  client/src/Components/HeaderBar/topRightBar.js
  client/src/Components/ListItem/bottomButton.js
  client/src/Components/ListItem/itemCard.js
  client/src/Components/ListItem/mainItemCard.js
  client/src/Lib/constant.js
  client/src/Lib/utils.js
  client/src/Navigator/MainTab/Designer/brandingTabScreen.js
  client/src/Navigator/MainTab/designerTabStack.js
  client/src/Screen/01_FirstTab/User/designerStyleScreen.js
  client/src/Screen/02_SecondTab/Designer/processBidListScreen.js
  client/src/Screen/02_SecondTab/Designer/waitBidListScreen.js
  client/src/Screen/03_ThirdTab/Designer/brandingListScreen.js
  client/src/Screen/03_ThirdTab/Designer/brandingMainScreen.js
  client/src/Screen/03_ThirdTab/Designer/createBrandingScreen.js
  client/src/Screen/03_ThirdTab/Designer/detailBrandingScreen.js
  client/src/Screen/03_ThirdTab/Designer/editBrandingScreen.js
  client/src/Screen/03_ThirdTab/Designer/index.js
  client/src/Screen/03_ThirdTab/Designer/styleBookScreen.js
  client/yarn.lock
  server/models/branding.js
  server/models/index.js
  server/models/style.js
  server/models/user.js
  server/routes/branding/controller.js
  server/routes/branding/index.js
  server/services/branding.js
  server/services/db/bid.js
  server/services/db/branding.js
Labels: 📚 api, 📡 backend, 🖼️ frontend

#59 [Designer-FirstTab] 유저 제안서 Search 부분 Issue 정리
  client/package-lock.json
  client/package.json
  client/src/Components/Bid/bidCategory.js
  client/src/Components/Card/cardChangeStyle.js
  client/src/Components/Card/cardInfo.js
  client/src/Components/Card/cardStyle.js
  client/src/Components/ListItem/itemCard.js
  client/src/Screen/01_FirstTab/Designer/createBidScreen.js
  client/src/Screen/01_FirstTab/Designer/proposalDetailScreen.js
  client/src/Screen/01_FirstTab/Designer/proposalListScreen.js
  client/yarn.lock
  server/models/style.js
  server/services/bid.js
  server/services/branding.js
  server/services/db/bid.js
  server/services/db/branding.js
  server/services/db/proposal.js
  server/services/proposal.js
Labels: 📚 api, 🚀refactor

#62 [DM] socket.io 기본 설정
  client/package-lock.json
  client/package.json
  client/src/Components/DM/chatBubble.js
  client/src/Components/DM/chatBubbleList.js
  client/src/Screen/DM/directMessageScreen.js
  client/src/Screen/DM/useChat.js
  client/yarn.lock
  server/app.js
  server/lib/event-name.js
  server/package-lock.json
  server/package.json
  server/socket/event/socket-event.js
  server/socket/handler/socket-handler.js
  server/socket/index.js
  server/socket/init-socket.js
  server/socket/socket.js
Labels: 📡 backend, 🖼️ frontend, 🚀refactor

#66 [Designer-FirstTab] 제안서 스와이프 카드 디자인 변경
  client/src/Components/Card/cardChangeStyle.js
  client/src/Screen/01_FirstTab/Designer/proposalListScreen.js
Labels: 🖼️ frontend

#68 디자이너 2,3번째 tab Refactoring 작업 수행
  client/ios/bidi.xcodeproj/project.pbxproj
  client/package-lock.json
  client/public/img/noBidList.jpg
  client/src/Components/Common/line.js
  client/src/Components/ListItem/itemBottomBtn.js
  client/src/Components/ListItem/itemCard.js
  client/src/Components/ListItem/itemContent.js
  client/src/Components/ListItem/itemHeader.js
  client/src/Components/ListItem/mainItemCard.js
  client/src/Navigator/MainTab/Designer/bidTabScreen.js
  client/src/Screen/01_FirstTab/Designer/proposalDetailScreen.js
  client/src/Screen/01_FirstTab/Designer/proposalListScreen.js
  client/src/Screen/02_SecondTab/Designer/bidMainScreen.js
  client/src/Screen/02_SecondTab/Designer/noBidListScreen.js
  client/src/Screen/02_SecondTab/Designer/noProcessBidList.js
  client/src/Screen/02_SecondTab/Designer/noWaitBidListScreen.js
  client/src/Screen/02_SecondTab/Designer/processBidListScreen.js
  client/src/Screen/02_SecondTab/Designer/waitBidListScreen.js
  client/src/Screen/03_ThirdTab/Designer/brandingListScreen.js
  client/yarn.lock
  server/services/db/bid.js
  server/services/db/branding.js
Labels: 🚀refactor

#71 [Designer-FourthTab] 히스토리/리뷰 관리
  client/src/Components/Card/cardDisableStyle.js
  client/src/Components/Card/cardInfo.js
  client/src/Components/ListItem/itemContent.js
  client/src/Components/ListItem/itemHeader.js
  client/src/Navigator/MainTab/Designer/historyTabScreen.js
  client/src/Navigator/MainTab/designerTabStack.js
  client/src/Screen/02_SecondTab/Designer/processBidListScreen.js
  client/src/Screen/02_SecondTab/Designer/waitBidListScreen.js
  client/src/Screen/03_ThirdTab/Designer/brandingListScreen.js
  client/src/Screen/04_FourthTab/Designer/historyDetailScreen.js
  client/src/Screen/04_FourthTab/Designer/historyMainScreen.js
  client/src/Screen/04_FourthTab/Designer/histroyListScreen.js
  client/src/Screen/04_FourthTab/Designer/index.js
  client/src/Screen/04_FourthTab/Designer/noHistoryListScreen.js
  client/src/Screen/04_FourthTab/Designer/noReviewListScreen.js
  client/src/Screen/04_FourthTab/Designer/reviewListScreen.js
  server/services/matchingHistory.js
Labels: 🖼️ frontend

#72 [DM] Customer socket.io 설정 및 client side 수정(연결)
  client/ios/bidi.xcodeproj/project.pbxproj
  client/package-lock.json
  client/src/Components/DM/cardList.js
  client/src/Components/DM/cardListItem.js
  client/src/Components/DM/chatBubble.js
  client/src/Components/DM/chatBubbleList.js
  client/src/Components/DM/dMHeader.js
  client/src/Components/ListItem/itemCard.js
  client/src/Components/Modal/styleModal.js
  client/src/Lib/socket/emits/socket.js
  client/src/Lib/socket/socketIO.js
  client/src/Lib/socket/types/socket-types.js
  client/src/Screen/Auth/loginScreen.js
  client/src/Screen/DM/directMessageScreen.js
  client/src/Screen/DM/messageListScreen.js
  client/src/Screen/DM/useChat.js
  client/yarn.lock
  server/lib/event-name.js
  server/models/index.js
  server/models/message.js
  server/models/room.js
  server/routes/index.js
  server/routes/message/controller.js
  server/routes/message/index.js
  server/routes/room/controller.js
  server/routes/room/index.js
  server/services/db/bid.js
  server/services/db/message.js
  server/services/db/room.js
  server/services/message.js
  server/services/room.js
  server/socket/event/socket-event.js
  server/socket/handler/socket-handler.js
  server/socket/index.js
  server/socket/init-socket.js
Labels: 📚 api, 📡 backend, 🖼️ frontend

#84 Client API 모듈화 및 Redux 구현
  client/.eslintrc.js
  client/index.js
  client/ios/bidi.xcodeproj/project.pbxproj
  client/ios/bidi/bidi.entitlements
  client/package-lock.json
  client/package.json
  client/src/Api/bid.js
  client/src/Api/branding.js
  client/src/Api/common.js
  client/src/Api/matchingHistory.js
  client/src/Api/user.js
  client/src/Components/Card/cardStyle.js
  client/src/Contexts/Common/asyncUtils.js
  client/src/Contexts/Common/globalStore.js
  client/src/Contexts/User/action.js
  client/src/Contexts/User/constant.js
  client/src/Contexts/User/index.js
  client/src/Contexts/User/reducer.js
  client/src/Contexts/index.js
  client/src/Lib/constant.js
  client/src/Lib/utils.js
  client/src/Navigator/MainTab/mainTabStack.js
  client/src/Screen/01_FirstTab/Designer/proposalListScreen.js
  client/src/Screen/01_FirstTab/User/designerListScreen.js
  client/src/Screen/Auth/loginScreen.js
  client/src/Screen/Auth/registerScreen.js
  client/src/Screen/landingScreen.js
  client/yarn.lock
  server/middleware/getLastUserId.js
  server/middleware/upload.js
  server/routes/user/controller.js
  server/routes/user/index.js
  server/services/db/user.js
  server/services/user.js
Labels: 📡 backend, 🖼️ frontend, 🚀refactor

#87 DB/API 최적화 완료
  server/app.js
  server/lib/asyncWrapper.js
  server/lib/constants.js
  server/middleware/getLastUserId.js
  server/models/index.js
  server/models/matching.js
  server/routes/bid/controller.js
  server/routes/bid/index.js
  server/routes/branding/controller.js
  server/routes/branding/index.js
  server/routes/index.js
  server/routes/matching/controller.js
  server/routes/matching/index.js
  server/routes/message/controller.js
  server/routes/message/index.js
  server/routes/proposal/controller.js
  server/routes/proposal/index.js
  server/routes/room/controller.js
  server/routes/room/index.js
  server/routes/style/controller.js
  server/routes/style/index.js
  server/routes/styleScrap/controller.js
  server/routes/styleScrap/index.js
  server/routes/user/controller.js
  server/routes/user/index.js
  server/services/bid.js
  server/services/branding.js
  server/services/db/bid.js
  server/services/db/branding.js
  server/services/db/matching.js
  server/services/db/matchingHistory.js
  server/services/db/proposal.js
  server/services/db/style.js
  server/services/db/styleScrap.js
  server/services/db/user.js
  server/services/matching.js
  server/services/matchingHistory.js
  server/services/proposal.js
  server/services/style.js
  server/services/styleScrap.js
  server/services/user.js
Labels: 📚 api, 📡 backend, 📑 documentation, 🚀refactor

#88 Bid Tab 리팩토링
  client/src/Api/bid.js
  client/src/Api/matching.js
  client/src/Api/matchingHistory.js
  client/src/Api/proposal.js
  client/src/Components/Bid/bidCategory.js
  client/src/Components/Bid/bidLetter.js
  client/src/Components/Bid/bidRefStyle.js
  client/src/Components/Card/cardChangeStyle.js
  client/src/Components/Card/cardStyle.js
  client/src/Components/Common/loading.js
  client/src/Components/ListItem/itemContent.js
  client/src/Contexts/Bid/action.js
  client/src/Contexts/Bid/constant.js
  client/src/Contexts/Bid/index.js
  client/src/Contexts/Bid/reducer.js
  client/src/Contexts/Common/asyncUtils.js
  client/src/Contexts/Common/globalStore.js
  client/src/Contexts/Matching/action.js
  client/src/Contexts/Matching/constant.js
  client/src/Contexts/Matching/index.js
  client/src/Contexts/Matching/reducer.js
  client/src/Contexts/Proposal/action.js
  client/src/Contexts/Proposal/constant.js
  client/src/Contexts/Proposal/index.js
  client/src/Contexts/Proposal/reducer.js
  client/src/Contexts/User/action.js
  client/src/Contexts/User/constant.js
  client/src/Contexts/User/reducer.js
  client/src/Lib/constant.js
  client/src/Navigator/MainTab/Designer/bidTabScreen.js
  client/src/Navigator/MainTab/mainTabStack.js
  client/src/Screen/01_FirstTab/Designer/createBidScreen.js
  client/src/Screen/01_FirstTab/Designer/proposalDetailScreen.js
  client/src/Screen/01_FirstTab/Designer/proposalListScreen.js
  client/src/Screen/02_SecondTab/Designer/.detailBidScreen.js.swp
  client/src/Screen/02_SecondTab/Designer/bidMainScreen.js
  client/src/Screen/02_SecondTab/Designer/detailBidScreen.js
  client/src/Screen/02_SecondTab/Designer/processBidListScreen.js
  client/src/Screen/02_SecondTab/Designer/waitBidListScreen.js
  client/src/Screen/Auth/registerScreen.js
  server/middleware/upload.js
  server/routes/matching/controller.js
  server/routes/matching/index.js
  server/services/bid.js
Labels: 📚 api, 📡 backend, 🖼️ frontend, 🚀refactor
